### ISSUE TITLE
an error is appearing when you are exiting the recycle 

### ISSUE THREAD

**Issue by luneargr** [VoidHubScripts/vhs-recycle#1]
![Screenshot 2024-07-04 234316](https://github.com/VoidHubScripts/vhs-recycle/assets/75813200/a5586714-b683-4017-ba9d-40b7cf28c741)

I am using qbox framework

**Comment by VoidHubScripts** [comment]
Fixed the error was just a missing vector for the peds heading, should affect anything in-game but it's sorted

**Comment by VoidHubScripts** [comment]
Fixed the error was just a missing vector for the peds heading, should affect anything in-game but it's sorted
